name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.5'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
#         env:
#           TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#           TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        run: terraform plan -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" -var "aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"  -destroy -out=tfplan

      - name: Terraform Destroy
        if: success() && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
