name: AWS Nuke

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-3

jobs:
  aws-nuke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Install AWS Nuke
        run: |
          wget -c https://github.com/rebuy-de/aws-nuke/releases/download/v2.21.2/aws-nuke-v2.21.2-linux-amd64.tar.gz
          tar -xvf aws-nuke-v2.21.2-linux-amd64.tar.gz
          mv aws-nuke-v2.21.2-linux-amd64 nuke
          chmod +x nuke
          sudo mv nuke /usr/local/bin/nuke

      - name: Run AWS Nuke
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          nuke --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} \
               --force --no-dry-run
               
       # --max-concurrent-regions 10 --max-concurrent-deletes 50 \
            #   --excluded-regions us-east-1 --skip-resource-types '^(AWS|Reserved)::*' \
              
    # --skip-tags 'user:jane'
